# Generated by Django 3.1.4 on 2020-12-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201209_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='hours',
            field=models.CharField(max_length=255),
        ),
    ]
