# Generated by Django 3.1.4 on 2020-12-10 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20201209_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.ForeignKey(default='leave a comment', max_length=255, on_delete=django.db.models.deletion.CASCADE, to='shop.comments'),
        ),
    ]
